# Generated by Django 4.1.3 on 2022-12-05 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_partners_buyer_partners_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('number', models.CharField(max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myshop.companies')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myshop.partners')),
            ],
            options={
                'verbose_name': 'Договоры',
                'verbose_name_plural': 'Договор',
            },
        ),
    ]
