# Generated by Django 4.1.3 on 2022-12-05 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_title', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('unit_izm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myshop.unitizm')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Товар/Услуга',
            },
        ),
    ]
