# Generated by Django 4.1.3 on 2022-12-05 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_title', models.CharField(max_length=30)),
                ('bik', models.CharField(max_length=9)),
                ('korr', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Банки',
                'verbose_name_plural': 'Банк',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=30)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myshop.banks')),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='myshop.companies')),
                ('partner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='myshop.partners')),
            ],
            options={
                'verbose_name': 'Банковские счета',
                'verbose_name_plural': 'Банковский счет',
            },
        ),
    ]
